export const COURSE = 'COURSE'
export const LESSON = 'LESSON'
export const EDUCATION_PROGRAM = 'EDUCATION_PROGRAM'
export const SUBJECT = 'SUBJECT'
export const USER = 'USER'
export const FACULTY = 'FACULTY'
export const TRAINING_DIRECTION = 'TRAINING_DIRECTION'